# Generated by Django 4.2.4 on 2023-08-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='items',
            new_name='item',
        ),
    ]
